# DEPLOYMENT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaosforge-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chaosforge

  template:
    metadata:
      labels:
        app: chaosforge
    spec:
      nodeSelector:
        type: {{ .Values.nodeSelector.type }}

      containers:
        - name: chaosforge
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 5050

          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"

            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"

          livenessProbe:
            httpGet:
              path: /health
              port: 5050
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /health
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 3

---

# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: chaosforge-service
spec:
  selector:
    app: chaosforge

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: "{{ .Values.service.type }}"


