apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaosforge
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/nsahil992/chaosforge.git
    targetRevision: master
    path: helm

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: chaosforge

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
