name: ChaosForge CI/CD Pipeline

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - feature/**

    paths:
      - "app/**"
      - "Dockerfile"
      - "requirements.txt"
      - ".github/workflows/**"
      - "helm/**"
      - "argocd/**"

jobs:
  ci:
    name: Build, Test, and Push Docker Image
    runs-on: self-hosted

    env:
      VERSION: ${{ secrets.SEMVER_VERSION }}

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Verify Python Installation
        run: |
          python3 --version

      - name: Install dependencies
        run: make install

      - name: Validate application imports
        run: make validate

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Test
        run: make docker-test

      - name: Docker Build and Push
        run: |
          make docker-build VERSION=${{ env.VERSION }}
          make docker-push VERSION=${{ env.VERSION }}

  cd:
    name: GitOps CD (Helm Image Update)
    runs-on: self-hosted
    needs: ci

    if: github.ref == 'refs/heads/master'

    env:
      VERSION: ${{ secrets.SEMVER_VERSION }}

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Helm image tag
        run: |
          sed -i '' 's/tag:.*/tag: "'"${VERSION}"'"/' helm/values.yaml

      - name: Commit and push Helm changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add helm/values.yaml
          git commit -m "cd: update ChaosForge image tag to ${VERSION} [skip ci]" || echo "No changes"
          git push origin master
